### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mind8hunter**
improve Google dorks

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @mind8hunter 
Could you please explain the changes? I'm probably not smart enough to understand it immediately 😅

**Comment by mind8hunter** [comment]
sir  I  improve Google dorks
for any 1 find u r tool easily
using keywords 😇

**Comment by daniel-sc** [comment]
Hi @mind8hunter 
I understand you want to add keywords to improve the google ranking?
I only see headlines without content/text paragraphs at the end of the readme file - this looks awe full for any human reader. I don't think we should optimize for google only, but primarily for humans and google only second. 
Could you please improve this?

**Comment by mind8hunter** [comment]
yes sure accept the pull request then I edit
it again

**Comment by daniel-sc** [comment]
I'd rather have you update this PR or create a new one that is complete.

**Comment by mind8hunter** [comment]
If you can accept please
Because you accept then I get 1 point for my project
And don't worry I improve your tool

**Comment by daniel-sc** [comment]
Hi @mind8hunter 
Really appreciate you like the tool. But this PR does not meet the quality standards: https://hacktoberfest.digitalocean.com/details#quality
I'll need to decline this PR, but would be happy to look at new PR that provides real value. 
Best, Daniel

**Comment by mind8hunter** [comment]
ok i try to improve

**Pull request closed without merging**
